""" File to store discipline dictionary. """
disciplines = {
  "": "/phds",
  "agriculture": "/phds/agriculture/?10M720",
  "anthropology": "/phds/anthropology/?10M740",
  "architecture, building & planning": "/phds/architecture-building-and-planning/?10M760",
  "biological sciences": "/phds/biological-sciences/?10M780",
  "business & management": "/phds/business-and-management/?10M7a0",
  "chemistry": "/phds/chemistry/?10M7c0",
  "communication & media studies": "/phds/communication-and-media-studies/?10M7e0",
  "computer science": "/phds/computer-science/?10M7g0",
  "creative arts & design": "/phds/creative-arts-and-design/?10M7i0",
  "economics": "/phds/economics/?10M7k0",
  "education": "/phds/education/?10M7m0",
  "engineering": "/phds/engineering/?10M7o0",
  "environmental sciences": "/phds/environmental-sciences/?10M7q0",
  "finance": "/phds/finance/?10M7s0",
  "food sciences": "/phds/food-sciences/?10M7u0",
  "forensic and archaeological sciences": "/phds/forensic-and-archaeological-sciences/?10M7w0",
  "geography": "/phds/geography/?10M7y0",
  "geology": "/phds/geology/?10M7A0",
  "history & archaeology": "/phds/history-and-archaeology/?10M7C0",
  "information services": "/phds/information-services/?10M7E0",
  "languages, literature & culture": "/phds/languages-literature-and-culture/?10M7G0",
  "law": "/phds/law/?10M7I0",
  "linguistics & classics": "/phds/linguistics-and-classics/?10M7K0",
  "materials science": "/phds/materials-science/?10M7M0",
  "mathematics": "/phds/mathematics/?10M7O0",
  "medicine": "/phds/medicine/?10M7Q0",
  "nursing & health": "/phds/nursing-and-health/?10M7S0",
  "philosophy": "/phds/philosophy/?10M7U0",
  "physics": "/phds/physics/?10M7W0",
  "politics & government": "/phds/politics-and-government/?10M7Y0",
  "psychology": "/phds/psychology/?10M7-0",
  "sociology": "/phds/sociology/?10M701",
  "sport & exercise science": "/phds/sport-and-exercise-science/?10M721",
  "theology & religious studies": "/phds/theology-and-religious-studies/?10M741",
  "veterinary sciences": "/phds/veterinary-sciences/?10M761"
}